name: ExtDN M2 Mess Detector
on: [workflow_call]

jobs:
  phpmd:
    name: M2 Mess Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extdn/github-actions-m2/magento-mess-detector@master
